# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: beetlebot_gripper
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - j_base_2
    - j_lower_arm_3
    - j_upper_arm_3
    - j_gripper_4
    - j_gripper_claw_1
    - j_gripper_claw_2
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: beetlebot_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - j_base_2
      - j_lower_arm_3
      - j_upper_arm_3
      - j_gripper_4
  - name: beetlebot_gripper_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - j_gripper_claw_1
      - j_gripper_claw_2
followposition:
  type: position_controllers/JointPositionController
  joints:
    - j_base_2
    - j_lower_arm_3
    - j_upper_arm_3
    - j_gripper_4
    - j_gripper_claw_1
    - j_gripper_claw_2
  gains:
    j_base_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    j_lower_arm_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    j_upper_arm_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    j_gripper_4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    j_gripper_claw_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    j_gripper_claw_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1